### PR TITLE
Fix warn_unused_result warnings (errors)

### PR DESCRIPTION
**Pull request by omidaladini**
Encountered on Ubuntu 14.04.1 LTS with:
- gcc 4.8.2-19ubuntu1
- libc6 2.19-0ubuntu6.5

which due to `-Werror` prevents bruce to compile.

### CODE REVIEW

**Comment by dspeterson** [comment]
The changes to server/daemonize.cc look good.  However, for bruce/discard_file_logger.cc and bruce/debug/debug_setup.cc, it would be better to write a syslog message rather than using IfLt0(), since IfLt0() will throw a fatal exception and we don't want bruce to shut down if one of these calls fails.

**Comment by omidaladini** [comment]
Regarding the truncate calls in src/bruce/debug/debug_setup.cc, I agree that there is no need to throw an exception.

In case of the one at src/bruce/discard_file_logger.cc, the CreateDir function will only be called at the server start. Isn't it better to fail if it can't create the discard log directory in the first place? Otherwise it cascades into other errors. For example, currently it crashes due to an [exception thrown later on](https://github.com/tagged/bruce/blob/master/src/bruce/discard_file_logger.cc#L718) if the discard directory hadn't been made successfully:

```
2015-02-27T14:28:12.67788 |srv=bruce|bruce[8689]: Discard logfile: [/tmp/non_writable_dir/non_existent_dir/nondiscard_log_file]
2015-02-27T14:28:12.67792 |srv=bruce|bruce[8689]: Discard log max file size: 1024 kbytes
2015-02-27T14:28:12.67797 |srv=bruce|bruce[8689]: Discard log max archive size: 8192 kbytes
2015-02-27T14:28:12.67801 |srv=bruce|bruce[8689]: Discard log bad msg prefix size: 256 bytes
2015-02-27T14:28:12.67806 |srv=bruce|bruce[8689]: Discard report bad msg prefix size: 256 bytes
2015-02-27T14:28:12.67810 |srv=bruce|bruce[8689]: Automatic topic creation enabled
2015-02-27T14:28:12.67815 |srv=bruce|bruce[8689]: Retry on unknown partition enabled
2015-02-27T14:28:12.67819 |srv=bruce|bruce[8689]: Using new input datagram format
2015-02-27T14:28:12.67824 |srv=bruce|bruce[8689]: Using new output format
2015-02-27T14:28:12.67829 |srv=bruce|bruce[8689]: Pool block size is 128 bytes
2015-02-27T14:28:12.67834 |srv=bruce|bruce[8689]: Server started
2015-02-27T14:28:12.67966 |srv=bruce|/bin/mkdir: cannot create directory '/tmp/non_writable_dir': Permission denied
2015-02-27T14:28:12.68011 |srv=bruce|bruce[8689]: Fatal error in main thread: No such file or directory
<crash>
```

Although perhaps this is a different issue to fix and the intention is not to crash as long as possible?

**Comment by dspeterson** [comment]
I just merged your other pull request.  It will probably be late Monday evening (California time) before I get to this one.  Thanks!

**Comment by dspeterson** [comment]
In the case of CreateDir() in src/bruce/discard_file_logger.cc, if the call to std::system() fails, let's write an error message to syslog before shutting down, rather than just using IfLt0().  When IfLt0() throws a fatal exception, the reported error message doesn't give the user a good idea of exactly where the error occurred, so it might not be clear that the error was associated with attempting to create the discard logging directory.  There are plenty of other places where this is an issue, and eventually I'd like to improve Bruce's error reporting to ease troubleshooting in places where IfLt0() is currently used, but that can wait for another day.  Also we may eventually want to let Bruce log an error and continue executing with discard file logging functionality disabled in the case where we can't create the directory (the debug logfile code in src/bruce/debug currently works this way), but I think we get by without that behavior for now.

**Comment by dspeterson** [comment]
Ok, I just merged your pull request, with a few minor changes.  Thanks :-)

**Comment by omidaladini** [comment]
Perfect. Thanks!

**Pull request merged**
